[package]
name = "BitcodeRecompiler"
version = "0.1.0"
authors = ["penguin-wwy <940375606@qq.com>"]

[dependencies]
xml-rs = "0.7"
mach_object = "0.1.10"
failure = "0.1"
memmap = "0.6"
getopts = "0.2"
